<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Wedding Website Contact  Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'thanks-for-contacting.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'betsgarner@gmail.com',
		'to' => 'betsgarner@gmail.com,andrew.t.harvard@gmail.com'
	),
	'fields' => array(
		'custom_U8644' => array(
			'type' => 'string',
			'label' => 'Your Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your Name\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Your Email Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your Email Address\' is required.',
				'format' => 'Field \'Your Email Address\' has an invalid email.'
			)
		),
		'custom_U8639' => array(
			'type' => 'string',
			'label' => 'Your Message',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
